### PR TITLE
UI redesign

### PR DESCRIPTION
**Pull request by nebocoder**
Here is the redesign, please review it and tell me if any fixes are needed 😊 

#### Screenshot:

image

Note: I think the 2 images not loading has to do with the fact this screenshot was taken while running on localhost.

### CODE REVIEW

**Comment by error401de** [comment]
Thank you so much, this is looking really awesome!

2 questions:
- On my 13.6" Macbook I don't get the full content into my screen, I need to scroll. Can you try to play a little bit with the paddings, e.g. between boxes and header, the box titles to the box top or within the table lines, to support smaller screens?
- In mobile view the grey boxes reach to the border of the display (see screenshot for Galaxy S21 dimensions). Could you give them a small border (as it is currently)? Would look a little better IMHO

image

**Comment by error401de** [comment]
Looking at the screenshot again I just saw that it's not 100% centered, I can also scroll left and right, so I fear the mobile view is not fully working yet

**Comment by error401de** [comment]
Hi again @nebocoder,
I already merged (and released) this change to keep the potential conflicts for the next changes as low as possible :)
I will create tickets for the mentioned topics, if you have time to help it would be much appreciated, especially for the issue with the mobile view.

Again: Thanks a lot!

**Comment by nebocoder** [comment]
Hello @error401de, I will gladly fix the mobile view issues and try to improve padding to fit more content on larger screens.

**Comment by error401de** [comment]
Thanks @nebocoder ! I created #20 and #21 as follow ups :) I think I can only assign if you leave a short comment in it :)

**Pull request merged**
