### PR TITLE
#24 Dynamic highlighting

### PR DESCRIPTION
**Pull request by palaksv**
Checked if St Pauli is team1 or team2 and based upon the scores, highlighted the background

- Red for loss
- Green for win
- Yellow for draw

### CODE REVIEW

**Comment by error401de** [comment]
You have changed tabs to spaces, which makes it impossible to compare the files properly, can you please avoid that?
Also API calls are changed. We can discuss refinements, but we should separate this as it is hard to keep track on the actual changes otherwise.

There is a lot of code redundancy, which should be avoided:
In the if-statements you are setting the exact same `innerHTML` 6 times. In the logic you are applying you would only need to apply the class (`classList.add`) as content of `innerHTML` doesn't change.

**Comment by palaksv** [comment]
Okay, I'll take care of that. 
What are the new API calls?

**Comment by error401de** [comment]
I am very sorry for the late reply, I totally missed the mail notification.
No sorry, you got me wrong there. The API calls didn't change, you changed the syntax of it by adding line breaks. What I meant is only that we should separate functionality changes from refining other syntax to keep the commits clean :)

**Comment by palaksv** [comment]
It's alright. What should I do then? I have removed the code redundancy.

**Comment by error401de** [comment]
There is no change since my last comments? Last one is from 6 days ago.

**Comment by error401de** [comment]
replaced by #33

**Pull request closed without merging**
